'''title'''
__title__ = 'pikachupytools'
'''description'''
__description__ = 'Pytools: Some useful tools written by pure python.'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/pytools'
'''version'''
__version__ = '0.1.16'
'''author'''
__author__ = 'Charles'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2020-2022 Zhenchao Jin'